/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MessageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'sentAt' : Timestamp,
  'recipientId' : UserId,
  'senderId' : UserId,
});
export const ConversationSummary = IDL.Record({
  'lastMessage' : IDL.Opt(Message),
  'friendId' : UserId,
  'lastActivityAt' : Timestamp,
});
export const Friend = IDL.Record({ 'userId' : UserId, 'addedAt' : Timestamp });

export const idlService = IDL.Service({
  '__friendsStore' : IDL.Func([], [IDL.Reserved], ['query']),
  '__messageCounter' : IDL.Func([], [IDL.Reserved], ['query']),
  '__messageStore' : IDL.Func([], [IDL.Reserved], ['query']),
  'addFriend' : IDL.Func([IDL.Principal], [], []),
  'getMessageHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'listFriends' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
  'removeFriend' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [Message], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MessageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'sentAt' : Timestamp,
    'recipientId' : UserId,
    'senderId' : UserId,
  });
  const ConversationSummary = IDL.Record({
    'lastMessage' : IDL.Opt(Message),
    'friendId' : UserId,
    'lastActivityAt' : Timestamp,
  });
  const Friend = IDL.Record({ 'userId' : UserId, 'addedAt' : Timestamp });
  
  return IDL.Service({
    '__friendsStore' : IDL.Func([], [IDL.Reserved], ['query']),
    '__messageCounter' : IDL.Func([], [IDL.Reserved], ['query']),
    '__messageStore' : IDL.Func([], [IDL.Reserved], ['query']),
    'addFriend' : IDL.Func([IDL.Principal], [], []),
    'getMessageHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'listFriends' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
    'removeFriend' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [Message], []),
  });
};

export const init = ({ IDL }) => { return []; };